# Numpy
* numerical python or numeric python
* numpy is a programming language that deals with multi-dimensional arrays and matrices
* numpy supports a large number of mathematical operations

# why use numpy
* numpy is memory efficiency,meaning it can handle the vast amount of data more accessible than any other library
* especially for matrix multiplication and reshaping
* on top of that,numpy is fast.in fact,tensorflow and scikit.

# how to install numpy
* numpy is installed by default in anaconda

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.19.2


In [5]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [11]:
data=np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)
print(a1^a2)

[ 5  9 13 17]
[1 1 1 1]
[ 6 20 42 72]
[1.5        1.25       1.16666667 1.125     ]
[1 1 1 1]
[1 1 1 1]


In [15]:
data=np.array([[1,2,3,4],[5,6,7,8]])
#data1=np.array([[1.0,2.2,3.3,4.4],[5.5,6.6,7.7,8.8]])
print(np.shape(data))
print(data.dtype)

(2, 4)
int32


In [18]:
data1=np.array([[1.0,2.2,3.3,4.4],[5.5,6.6,7.7,8.8]])
print(np.shape(data1))
print(data1.dtype)

(2, 4)
float64


In [19]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [22]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [23]:
#numpy reshape
data2=np.array([[1,2,3,4],[5,6,7,8]])
print(data2)
data2.reshape((4,2))

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
#numpy flatten
data2=np.array([[1,2,3,4],[5,6,7,8]])
print(data2)
data2.flatten()

[[1 2 3 4]
 [5 6 7 8]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
#numpy hstack(data apended horizontally)
print(a1)
print(a2)
np.hstack((a1,a2))

[3 5 7 9]
[2 4 6 8]


array([3, 5, 7, 9, 2, 4, 6, 8])

In [26]:
#numpy hstack(data apended vertically)
print(a1)
print(a2)
np.vstack((a1,a2))

[3 5 7 9]
[2 4 6 8]


array([[3, 5, 7, 9],
       [2, 4, 6, 8]])

In [27]:
# to calculate mean
data2.mean()

4.5

In [28]:
#to calculate standard deviation
print(data)
data.std()

[[1 2 3 4]
 [5 6 7 8]]


2.29128784747792

In [34]:
#generate random numbers
d=np.random.randint(1,30,(3,3))
print(d)

[[22 21 10]
 [25  9 10]
 [26  3 21]]


In [33]:
print(data2)
print(data2.mean())
print(np.median(data2))
print(np.mod(2,3))

[[1 2 3 4]
 [5 6 7 8]]
4.5
4.5
2


In [35]:
np.random.normal(5,4,10)

array([ 4.40869913,  7.39509508,  4.86578948,  4.46473102,  0.16628138,
        7.59252154,  9.57965113,  7.73553702,  6.38620332, -4.21095839])

In [36]:
d.min()

3

In [37]:
d.mean()

16.333333333333332

In [38]:
d.std()

7.859884081701064

In [39]:
d.max()

26

In [40]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
a1.dot(a2)

140

In [42]:
a=np.repeat([1,2,3,4],3)
print(a)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [43]:
#arange function
#syntax-->arange(start,stop,step)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [45]:
#numpy linspace(default=50)
#syntax ---->linspace(start,stop,endpoint)
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [46]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [47]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [48]:
print(x)
x[:,1]

[[1 2 3 4]
 [5 6 7 8]]


array([2, 6])

# pandas
* pandas is opensource library that allows to perform data manipulation(series,dataframes)
* derived from PANel data
# why use pandas
* to handle missing data
* efficient way to slice the data
* flexible way to merge,concatenate and reshape data
# data structures
* series
* data frames
# series
* it is one dimensional data


In [51]:
import pandas as pd
s='python'
pd.Series(s)

0    python
dtype: object

In [52]:
import pandas as pd
pd.Series([1,2,3],index=[1,2,3])

1    1
2    2
3    3
dtype: int64

In [54]:
import pandas as pd
s='python workshop'
pd.Series(s,index=['a','b'])

a    python workshop
b    python workshop
dtype: object

In [55]:
k=input().split()
pd.Series(k)

python workshop


0      python
1    workshop
dtype: object

In [59]:
d1=pd.Series(['sahithi',28,'CSE',1,2],index=[1,2,3,4,5])

In [60]:
d1


1    sahithi
2         28
3        CSE
4          1
5          2
dtype: object

In [61]:
d1[:]

1    sahithi
2         28
3        CSE
4          1
5          2
dtype: object

In [62]:
d1[0:3]

1    sahithi
2         28
3        CSE
dtype: object

In [64]:
#syntax
#l=[output loop]
l=[i**2 for i in range(1,10)]
l

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [73]:
l=[i**3 for i in range(1,10)]
pd.Series(l)

0      1
1      8
2     27
3     64
4    125
5    216
6    343
7    512
8    729
dtype: int64

In [70]:
l=[i**4 for i in range(1,10)]
pd.Series(l)

0       1
1      16
2      81
3     256
4     625
5    1296
6    2401
7    4096
8    6561
dtype: int64